- name: "Configure chrony.conf"
  template:
    src: chrony.conf.j2
    dest: "/etc/chrony/chrony.conf"
    owner: root
    group: root
    mode: '0644'

- name: "Enabling chrony service"
  systemd:
    name: chrony
    state: restarted
    enabled: yes
    daemon_reload: yes