- name: Change TimeZone to Europe/Moscow
  shell: timedatectl set-timezone Europe/Moscow

- name: Changes for History
  shell: |
    echo "export HISTTIMEFORMAT='%F %T '" >> /root/.bashrc
    echo "export HISTSIZE=10000" >> /root/.bashrc
    echo "export HISTCONTROL=ignorespace" >> /root/.bashrc

- name: remove pkgs
  apt:
    name: ["snapd", "cloud-init", "aide", "ufw", "cloud-guest-utils"]
    state: absent
    purge: yes
    autoremove: yes

- name: Disable apparmor service
  systemd:
    name: apparmor
    state: stopped
    enabled: no

- name: Disable apparmor in grub
  copy:
    dest: /etc/default/grub.d/apparmor.cfg
    mode: 0644
    owner: root
    group: root
    content: |
      GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX apparmor=0"

- name: grub settings
  copy:
    dest: /etc/default/grub.d/ceph.cfg
    mode: 0644
    owner: root
    group: root
    content: |
      GRUB_CMDLINE_LINUX="${GRUB_CMDLINE_LINUX} nosoftlockup noautogroup mitigations=off"
      GRUB_CMDLINE_LINUX="${GRUB_CMDLINE_LINUX} processor.max_cstate=1 intel_idle.max_cstate=0 idle=halt cpuidle.off=1"
      GRUB_CMDLINE_LINUX="${GRUB_CMDLINE_LINUX} transparent_hugepage=madvise"

- name: update grub
  shell: update-grub2

- name: disable pager
  ansible.builtin.lineinfile:
    path: /etc/security/pam_env.conf
    line: SYSTEMD_PAGER DEFAULT=""

- name: configure cron.d sysstat
  copy:
    dest: /etc/cron.d/sysstat
    mode: 0644
    owner: root
    group: root
    content: |
      PATH=/usr/lib/sysstat:/usr/sbin:/usr/sbin:/usr/bin:/sbin:/bin
      53 23 * * * root /usr/lib/sysstat/sa2 -A
      */1 * * * * root /usr/lib/sysstat/sa1 1 1

- name: sysctl settings
  copy:
    dest: /etc/sysctl.d/99-ceph.conf
    mode: 0644
    owner: root
    group: root
    content: |
      kernel.pid_max=4194303
      fs.file-max=26234859
      fs.aio-max-nr=50000000
      vm.zone_reclaim_mode=0
      vm.vfs_cache_pressure=60
      vm.swappiness=10
      net.core.rmem_max=16777216
      net.core.wmem_max=16777216
      net.core.rmem_default=4194304
      net.core.wmem_default=4194304
      net.core.optmem_max=4194304
      net.ipv4.tcp_rmem = 4096 87380 16777216
      net.ipv4.tcp_wmem = 4096 16384 16777216
      net.ipv4.tcp_low_latency=1
      net.ipv4.tcp_sack=1
      net.ipv4.tcp_timestamps=0
      net.ipv4.tcp_adv_win_scale=1
      net.core.somaxconn=32768
      net.core.netdev_max_backlog=50000
      net.ipv4.tcp_fin_timeout=20
      vm.min_free_kbytes=4194304
      net.ipv4.tcp_slow_start_after_idle=0
      kernel.sched_autogroup_enabled=0
      net.ipv4.tcp_mtu_probing=0

- name: Masking ondemand.service
  ansible.builtin.systemd:
    name: ondemand.service
    masked: true

- name: Ring buffer
  copy:
    dest: /etc/networkd-dispatcher/routable.d/50-change-buffer
    mode: 0755
    owner: root
    group: root
    content: |
      #!/bin/sh
      for i in $(ip link show type bond_slave | grep UP | awk -F\: '{print $2}'); do
        ethtool -G $i tx $(ethtool -g $i | grep "Pre-set maximums" -A 4 | grep "TX:" | awk '{print $2}')
        ethtool -G $i rx $(ethtool -g $i | grep "Pre-set maximums" -A 4 | grep "RX:" | awk '{print $2}')
      done