- name: Install cephadm
  apt:
    name: "cephadm={{ ceph_repo_ver }}-1{{ ubuntu_codename }}"
    state: present
    update_cache: yes


- name: Change permissions for /var/lib/ceph
  file:
    path: /var/lib/ceph
    state: directory
    mode: '0755'
