- name: apt-get update
  apt:
    update_cache: yes

- name: install pkgs for UNIX
  apt:
    pkg:
      - sysstat
      - dnsutils
      - chrony
      - wget
      - curl
      - python-apt
      - python-apt-common
      - net-tools
      - ifenslave
      - rsyslog
      - dnsmasq
      - ipmitool
      - nvme-cli
      - lldpd
      - jq

- name: apt-get upgrade
  apt:
    upgrade: yes