- name: install podman
  apt:
    name: podman
    state: present

- name: configure insecure registry
  copy:
    dest: /etc/containers/registries.conf.d/ceph.conf
    mode: 0644
    owner: root
    group: root
    content: |
      [[registry]]
      location = "{{ local_registry }}"
      insecure = true

- name: configure TZ for podman
  copy:
    dest: /etc/containers/containers.conf
    mode: 0644
    owner: root
    group: root
    content: |
      [containers]
      tz = "local"
