- name: Collect mons info
  set_fact:
    mgr_nodes: "{{ groups['mons'] | map('regex_replace', '^(.*)$', '\\1.' +seg_fqdn) | join('; ') }}"
  when: "'mons' in group_names"

- name: Generate /home/cephorch/ceph_cluster.info file from template
  template:
    src: ceph_cluster-info.j2
    dest: /home/cephorch/ceph_cluster.info
    owner: root
  when: "'mons' in group_names"