---
# code: language=ansible

- hosts: "{{ srv }}"
  gather_facts: true
  become: true
  vars_files:
    - ../secrets/vault.yml
  roles:
    - role: preflight
      tags: [preflight]
    - role: bootstrap-dns
      tags: [network, dns]
    - role: set-hostname
      tags: [network, hostname]
    - role: apt-repos
      tags: [packages, repos]
    - role: ceph-service-users
      tags: [users]
    - role: base-packages
      tags: [packages]
    - role: podman
      tags: [packages, podman, ceph]
    - role: ceph-packages
      tags: [packages, ceph]
    - role: dnsmasq
      tags: [network, dns]
    - role: ntp
      tags: [network, ntp]
    - role: os-tune
      tags: [os]
    - role: raid-cli
      tags: [storage, raidcli]
    - role: extend-root-pv
      tags: [storage]
    - role: unix-users
      tags: [users]
црут ш ызусшан 